### ISSUE TITLE
unable to mount Ntfs Partition

### ISSUE THREAD

**Issue by y0ush4** [amonet-kamakiri/fireiso#2]
i really liked the fast booting of this build from usb and it runs hella fast i want to write it to the my laptop HDD with diff ntfs partition so what i did was i used a EASYBCD option to boot from iso direct from my HDD but i guess it does not have a NTFS-3G package included in it fails to boot further  
![IMG_0817](https://user-images.githubusercontent.com/39189703/121937719-9c72e380-cd68-11eb-92bd-52fee13c6210.JPG)

i request to please add support for it

**Comment by chaosmaster** [comment]
ntfs-3g is already included: https://github.com/amonet-kamakiri/fireiso/blob/master/archiso/packages#L104

I don't think you can boot off an NTFS volume.

**Comment by y0ush4** [comment]
How to install it along with windows 10 on HDD permanently with dual boot what’s the correct way?

**Comment by chaosmaster** [comment]
FireISO is a live-system not intended for installation.
It is based on [SystemRescueCD](https://www.system-rescue.org/) and they do have [some info for installing a disk](https://www.system-rescue.org/manual/Installing_SystemRescue_on_the_disk/)

**Comment by y0ush4** [comment]
Oh I see thanks for the prompt replies I think I can do that 

👍have a good day sir

**Comment by KittyBua** [comment]
Can you add system Install to HDD 

Slax Linux have this funktion in 1 sek - grub boot
