### ISSUE TITLE
Troubles with Writing ISO to USB

### ISSUE THREAD

**Issue by Ritterbrater** [amonet-kamakiri/fireiso#3]
Hi,

I had issues with booting the FireISO 2.0 iso. I used Rufus, Yumi, Unetbootin and always had an error message. E.g. an error with incompatible FAT filesystem.
But I would like to share a possible solution: Using Balena Etcher. It's also available in a portable version: https://github.com/balena-io/etcher

**Comment by Jake-Jensen** [comment]
> Hi,
> 
> I had issues with booting the FireISO 2.0 iso. I used Rufus, Yumi, Unetbootin and always had an error message. E.g. an error with incompatible FAT filesystem. But I would like to share a possible solution: Using Balena Etcher. It's also available in a portable version: https://github.com/balena-io/etcher

Had no issue writing with dd, Rufus, Unetbootin, nor DiskImager. 
This looks like an ad for Balena, which is known for violations of privacy.

**Comment by Ritterbrater** [comment]
> > Hi,
> > I had issues with booting the FireISO 2.0 iso. I used Rufus, Yumi, Unetbootin and always had an error message. E.g. an error with incompatible FAT filesystem. But I would like to share a possible solution: Using Balena Etcher. It's also available in a portable version: https://github.com/balena-io/etcher
> 
> Had no issue writing with dd, Rufus, Unetbootin, nor DiskImager. This looks like an ad for Balena, which is known for violations of privacy.

Sorry but I do not have any affiliation with balena etcher. Even more: I do not like that on their website only the setup version for Windows is provided by default.

Maybe re-think your argumentation: That these tools work for you does not inevidently mean that they work for everybody. I used the other tools already several times but in that particular case I had many troubles - maybe also a hardware issue with that USB key. I only wanted to give a small hint for those who also may have issues.

**Comment by dsacristan** [comment]
Yes, I had the same error burning the iso with rufus. Tryed several times with different usb's and two computers. Balena this time did the job. thanks for the post

**Comment by leao-nardo** [comment]
another issue for problems writing on usb ,. just use ventoy and copy the isos on usb way simpler . make the partition exfat which is default .
